### ISSUE TITLE
Schedules not updated

### ISSUE THREAD

**Issue by Hedgehawk11** [nicolaschan/bell#115]
The schedules are not reflected on the site. I am 98% sure it has something to do with this 
![image](https://github.com/nicolaschan/bell/assets/84346970/c9128ac3-0bc1-4f19-a50c-291f9489f8b3)

not being this: 
![image](https://github.com/nicolaschan/bell/assets/84346970/0dc06133-aae6-4a2b-b1a7-b9f3a372dd65)

I would open a PR but I don't want to mess something up(and I have no clue how to fix it)

**Comment by nicolaschan** [comment]
Thanks for the bug report! I'm trying to figure out how to reproduce this. I checked [bell.plus/egan](https://bell.plus/egan) and it seems to be using the minimum day today.

You can check which schedules are live on the website here: https://bell.plus/api/data/egan/calendar

We don't need to update the schedules submodule in this repo every time because there is a task on the server that pulls the latest one every few minutes.
