### ISSUE TITLE
Unit testing Tomcat server

### ISSUE THREAD

**Issue by nicolaschan** [nicolaschan/bell#28]
Kotlin server needs units tests. We should also integrate these tests into [travis](https://travis-ci.org/nicolaschan/bell) and our code coverage report.

**Comment by noloerino** [comment]
This isn't actually quite yet doable — the latest addition of web workers screwed things up a bit, and I'm trying to fix the directory structure so generated HTML doesn't require the `<base>` tag in order to resolve resource links. StackOverflow says this is because links resolve relative to Tomcat's WEB-INF folder, so maybe changing the location of those resources will resolve the issue.
