### ISSUE TITLE
Theme settings aren't saved after refresh

### ISSUE THREAD

**Issue by JamsheedMistri** [nicolaschan/bell#42]
https://youtu.be/lSBNTXnckDE

**Comment by nicolaschan** [comment]
Apparently this is caused by using http instead of https. When an unexpected error is encountered, the website resets its cookies (which include the theme) to try to fix itself. 

The error that is encountered in this case is: https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

To fix this, I now force https on the website.

**Comment by JamsheedMistri** [comment]
Can confirm, it's fixed.
